# Generated by Django 4.2.3 on 2024-06-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('Truck', 'Truck'), ('Push Cart', 'Push Cart'), ('Unknown', 'Unknown')], max_length=255)),
                ('location_description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('SUSPENDED', 'Suspended'), ('REQUESTED', 'Requested'), ('EXPIRED', 'Expired')], max_length=255)),
                ('food_items', models.JSONField()),
                ('x', models.TextField()),
                ('y', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
