# Generated by Django 4.2.3 on 2024-06-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0002_remove_foodtruck_latitude_remove_foodtruck_longitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foodtruck',
            index=models.Index(fields=['location'], name='location_idx'),
        ),
    ]
